apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - headlamp.yaml
  - https-redirect.yaml
  - ingress.yaml
  - rbac-oidc-viewers.yaml
  - rbac-viewer.yaml
