apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-viewer
  namespace: kube-system
  labels:
    app.kubernetes.io/name: headlamp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-viewer
  labels:
    app.kubernetes.io/name: headlamp
subjects:
  - kind: ServiceAccount
    name: headlamp-viewer
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
